server:
  port: 10012

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #云服务器端数据库
    url: jdbc:mysql://localhost:3306/weihuijuan?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
    hikari:
      minimum-idle: 3  # 最小空闲连接数量
      maximum-pool-size: 5  # 连接池最大连接数，默认是10
      max-lifetime: 1800000  # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-test-query: SELECT 1
  application:
    name: shop-service
  cloud:
    #nacos注册中心
    nacos:
      discovery:
        server-addr: localhost:8848


mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.campuscommunityapi.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# mybatis打印SQL语句
logging:
  level:
    com:
      campuscommunityapi:
        dao: debug

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中的表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

